background: white
height: 200
width: 200
antialiasing: false
colors:
  - name: magenta
    rgb: [1.0, 0, 1.0]
  - name: cyan
    rgb: [0, 1., 1.]
points:
  - ["center", [50, 50]]
objects:
  - name: l1
    type: line
    color: magenta
    start: [0, 50]
    end: [99, 99]
  - name: l2
    type: line
    color: cyan
    start: [0, 50]
    end: [99, 0]
  - name: red_line
    type: line
    color: red
    start: [50, 50]
    end: [30, 99]
  - name: green_line
    type: line
    color: green
    start: [50, 50]
    end: [30, 0]
  - name: blue_line
    type: line
    color: blue
    start: [50, 50]
    end: [99, 50]
  - name: gray_bar
    type: line
    color: mid_gray
    start: [80, 40]
    end: [80, 60]
  - type: polyline
    points: [[20, 40], [25, 60], [30, 40], [35, 60], [40, 40]]
  - type: polygon
    fill_color: magenta
    points: [[0, 0], [25, 10], [10, 40]]
  - type: polygon
    color: red
    fill_color: black
    points: [[80, 10], [88, 30], [94, 12]]
  - type: circle
    color: mid_gray
    center: center
    radius: 26
  - type: rect
    corner: [50, 20]
    height: 15
    width: 5
    color: blue
    fill_color: black
  - type: arc
    center: [100, 100]
    radius: 30
    arc: [0.75, 0.25]
