background: white
height: 100
width: 100
objects:
  - name: l1
    type: line
    start: [0, 50]
    end: [99, 99]
  - name: l2
    type: line
    start: [0, 50]
    end: [99, 0]
  - name: red_line
    type: line
    color: red
    start: [50, 50]
    end: [30, 99]
  - name: green_line
    type: line
    color: green
    start: [50, 50]
    end: [30, 0]
  - name: blue_line
    type: line
    color: blue
    start: [50, 50]
    end: [99, 50]
  - name: gray_bar
    type: line
    color: mid_gray
    start: [80, 40]
    end: [80, 60]



