background: white
height: 100
width: 100
objects:
  - l1:
    type: line
    color: black
    start: [0, 50]
    end: [99, 99]
  - l2:
    type: line
    color: black
    start: [0, 50]
    end: [99, 0]
  - red_line:
    type: line
    color: red
    start: [50, 50]
    end: [30, 99]
  - green_line:
    type: line
    color: green
    start: [50, 50]
    end: [30, 0]
  - blue_line:
    type: line
    color: blue
    start: [50, 50]
    end: [99, 50]
  - gray_bar:
    type: line
    color: mid_gray
    start: [80, 40]
    end: [80, 60]



